import 'package:drawee/constant/colors.dart';
import 'package:drawee/presentation/ui/login/strings.dart';
import 'package:drawee/presentation/ui/login/widgets/third_party_policy_link.dart';
import 'package:flutter/material.dart';

class PrivacyPolicy extends StatelessWidget {
  const PrivacyPolicy({
    super.key,
  });

  @override
  Widget build(BuildContext context) {
    Strings strings = Strings();
    return Center(
      child: GestureDetector(
        onTap: () {
          showModalBottomSheet<void>(
            context: context,
            builder: (context) {
              return Container(
                padding: const EdgeInsets.all(30),
                height: 400,
                decoration: BoxDecoration(
                  borderRadius: BorderRadius.circular(20),
                  color: AppColors.white,
                ),
                child: ListView(
                  children: [
                    // 제목 ----------------------------
                    const Text(
                      '개인정보 처리방침',
                      style: TextStyle(
                        fontWeight: FontWeight.w700,
                        fontSize: 16,
                      ),
                    ),
                    const SizedBox(
                      height: 16,
                    ),
                    titles('Privacy Policy'),
                    content(strings.privacyPolicy),
                    titles('Information Collection and Use'),
                    content(strings.informationCollectionAndUse),
                    titles('Third Party Access'),
                    content(strings.thirdPartyAccess[0]),
                    ThirdPartyPolicyLink(strings: strings),
                    content(strings.thirdPartyAccess[1]),
                    titles('Opt-Out Rights'),
                    content(strings.optOutRights),
                    titles('Data Retention Policy'),
                    content(strings.dataRetentionPolicy),
                    titles('Children'),
                    content(strings.chileren),
                    titles('Security'),
                    content(strings.security),
                    titles('Changes'),
                    content(strings.changesToThisTerms),
                    titles('Your Consent'),
                    content(strings.yourConsent),
                    titles('Contact Us'),
                    content(strings.contactUs),
                    // Terms & Conditions ----------------------------
                    const Text(
                      '이용 약관',
                      style: TextStyle(
                        fontWeight: FontWeight.w700,
                        fontSize: 16,
                      ),
                    ),
                    const SizedBox(
                      height: 16,
                    ),
                    titles('Terms & Conditions'),
                    content(strings.termsAndConditions),
                    // 외부 링크 ----------------------------
                    ThirdPartyPolicyLink(strings: strings),
                    content(strings.notifications),
                    // Changes to These Terms and Conditions ----------------------------
                    titles('Changes to These Terms and Conditions'),
                    content(strings.changes),
                    // Contact Us ----------------------------
                    titles('Contact Us'),
                    content(strings.contact),
                    Container(
                      width: double.infinity,
                      height: 1,
                      color: AppColors.gray,
                    ),
                    const SizedBox(
                      height: 16,
                    ),
                    content(
                        'This Terms and Conditions page was generated by App Privacy Policy Generator'),
                  ],
                ),
              );
            },
          );
        },
        child: const Text(
          '개인정보 처리방침',
          style: TextStyle(
            fontSize: 12,
            color: AppColors.darkGray,
          ),
        ),
      ),
    );
  }

  Text titles(String title) {
    return Text(
      title,
      style: const TextStyle(
        fontWeight: FontWeight.w500,
        fontSize: 14,
      ),
    );
  }

  Text content(String content) {
    return Text(
      content,
      style: const TextStyle(
        color: AppColors.darkGray,
      ),
    );
  }
}
