// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB5ror4bFDVqfO_RXwo-Gzvm6hZynV0IqI',
    appId: '1:1096456258246:android:d9c28b3f7b148922450dc7',
    messagingSenderId: '1096456258246',
    projectId: 'drawee-f84dc',
    storageBucket: 'drawee-f84dc.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCKT6wadJ8HpL8NUWPgF90A12nVDjHA1PI',
    appId: '1:1096456258246:ios:7e112101ae48f5cc450dc7',
    messagingSenderId: '1096456258246',
    projectId: 'drawee-f84dc',
    storageBucket: 'drawee-f84dc.firebasestorage.app',
    androidClientId: '1096456258246-c9ra4surogo8ogh9enoosha8l1hj71i9.apps.googleusercontent.com',
    iosClientId: '1096456258246-m706qi66f9s8t2ae3tegj3rd9it5vhq6.apps.googleusercontent.com',
    iosBundleId: 'com.oghs.drawee',
  );
}
